name: CI-CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: clone repo.
        uses: actions/checkout@v4

      - name: Build Docker Compose
        run: |
          docker compose build

      - name: Run Container
        run: |
          docker compose up -d

      - name: Status Check
        run: |
          docker ps

      - name: Stop Container
        run: |
          docker compose down

      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/outfit_reco

            git pull origin main

            docker compose down

            docker compose up -d --build